package com.mobileide.app.runtime

import android.content.Context
import android.net.ConnectivityManager
import android.util.Log
import java.io.File
import java.io.FileOutputStream
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress
import java.nio.ByteBuffer
import java.util.concurrent.atomic.AtomicInteger

/**
 * Publishes the small, device-owned part of a Linux guest filesystem.
 *
 * Linux-user binaries cannot read Android's resolver configuration through a
 * normal Linux `/etc/resolv.conf`: Android deliberately does not expose one.
 * QEMU's -L path prefix lets us provide only the compatibility files that are
 * different on Android while leaving the optional Linux runtime isolated from
 * ADEV's normal Bionic tools.
 */
class LinuxGuestCompatibility(
    context: Context,
    private val runtimeRoot: File
) {
    data class Snapshot(
        val dnsServers: List<String>,
        val upstreamDnsServers: List<String>,
        val dnsSource: String,
        val resolverFile: File?,
        val guestRoot: File?,
        val caBundleAvailable: Boolean
    )

    companion object {
        private const val TAG = "LinuxGuestCompat"
        private const val DNS_HEALTH_NAME = "example.com"
        private const val DNS_CACHE_MS = 5 * 60 * 1000L
        private val dnsQueryId = AtomicInteger(0x4a00)
        // Android normally supplies the network resolver through
        // LinkProperties. Some hotspot DNS proxies return non-conformant
        // answers that Linux libc accepts as the requested address. These
        // resolvers are used only after that condition is proved on-device.
        private val VERIFIED_FALLBACK_DNS = listOf(
            "1.1.1.1",
            "1.0.0.1",
            "2606:4700:4700::1111",
            "2606:4700:4700::1001"
        )
    }

    private data class ResolverSelection(
        val servers: List<String>,
        val upstream: List<String>,
        val source: String
    )

    private val connectivityManager =
        context.applicationContext.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
    private var cachedResolverKey: String? = null
    private var cachedResolverAt = 0L
    private var cachedResolver: ResolverSelection? = null

    @Synchronized
    fun refresh(): Snapshot {
        val linuxRoot = File(runtimeRoot, "linux")
        val installed = File(linuxRoot, "manifest.json").isFile
        val selection = selectDnsServers()
        val servers = selection.servers
        val resolverText = buildString {
            append("# Generated by ADEV; source=").append(selection.source).append(".\n")
            servers.forEach { append("nameserver ").append(it).append('\n') }
            append("options timeout:2 attempts:2\n")
        }

        // This path is also consumed by the optional glibc compatibility pack.
        val runtimeEtc = File(runtimeRoot, "etc")
        val runtimeResolver = File(runtimeEtc, "resolv.conf")
        writeIfChanged(runtimeResolver, resolverText, 0b110100100) // 0644

        var guestRoot: File? = null
        var caAvailable = false
        if (installed) {
            guestRoot = File(linuxRoot, "rootfs")
            val guestEtc = File(guestRoot, "etc")
            writeIfChanged(
                File(guestEtc, "hosts"),
                "127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n",
                0b110100100
            )
            writeIfChanged(
                File(guestEtc, "nsswitch.conf"),
                "hosts: files dns\nnetworks: files dns\n",
                0b110100100
            )
            writeIfChanged(File(guestEtc, "resolv.conf"), resolverText, 0b110100100)

            val caBundle = File(runtimeRoot, "etc/ssl/certs/ca-bundle.crt")
            caAvailable = caBundle.isFile && caBundle.length() > 0
            if (caAvailable) {
                copyIfChanged(caBundle, File(guestRoot, "etc/ssl/certs/ca-certificates.crt"))
                copyIfChanged(caBundle, File(guestRoot, "etc/ssl/cert.pem"))
            }
        }

        return Snapshot(
            servers,
            selection.upstream,
            selection.source,
            runtimeResolver,
            guestRoot,
            caAvailable
        )
    }

    private fun selectDnsServers(): ResolverSelection {
        val upstream = activeDnsServers()
        val activeNetwork = try { connectivityManager.activeNetwork } catch (_: Exception) { null }
        val key = "${activeNetwork?.toString().orEmpty()}|${upstream.joinToString(",")}"
        val now = android.os.SystemClock.elapsedRealtime()
        cachedResolver?.let { cached ->
            if (cachedResolverKey == key && now - cachedResolverAt < DNS_CACHE_MS) return cached
        }

        val healthyActive = upstream.filter { server ->
            dnsResponseIsSafe(server, activeNetwork)
        }
        val selection = if (healthyActive.isNotEmpty()) {
            ResolverSelection(healthyActive, upstream, "android-link-properties")
        } else {
            val fallbacks = VERIFIED_FALLBACK_DNS.filter { server ->
                dnsResponseIsSafe(server, activeNetwork)
            }
            if (fallbacks.isNotEmpty()) {
                Log.w(
                    TAG,
                    "Android DNS returned an unsafe Linux response; using verified fallback resolver"
                )
                ResolverSelection(fallbacks, upstream, "verified-fallback")
            } else {
                ResolverSelection(upstream, upstream, "android-unverified")
            }
        }
        cachedResolverKey = key
        cachedResolverAt = now
        cachedResolver = selection
        return selection
    }

    /**
     * Reject DNS servers that place unrelated A records in the answer section.
     * Android's netd tolerates a known hotspot implementation that does this,
     * but musl/glibc guests can select one of those unrelated addresses.
     */
    private fun dnsResponseIsSafe(server: String, network: android.net.Network?): Boolean {
        return try {
            val id = dnsQueryId.incrementAndGet() and 0xffff
            val query = buildDnsQuery(id, DNS_HEALTH_NAME)
            DatagramSocket().use { socket ->
                network?.bindSocket(socket)
                socket.soTimeout = 1_200
                val address = InetAddress.getByName(server)
                socket.send(DatagramPacket(query, query.size, address, 53))
                val bytes = ByteArray(4096)
                val response = DatagramPacket(bytes, bytes.size)
                socket.receive(response)
                validateDnsAnswer(bytes.copyOf(response.length), id, DNS_HEALTH_NAME)
            }
        } catch (_: Exception) {
            false
        }
    }

    private fun buildDnsQuery(id: Int, host: String): ByteArray {
        val output = java.io.ByteArrayOutputStream()
        output.write((id ushr 8) and 0xff)
        output.write(id and 0xff)
        output.write(byteArrayOf(0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00))
        host.split('.').forEach { label ->
            val encoded = label.toByteArray(Charsets.US_ASCII)
            output.write(encoded.size)
            output.write(encoded)
        }
        output.write(0)
        output.write(byteArrayOf(0x00, 0x01, 0x00, 0x01)) // A, IN
        return output.toByteArray()
    }

    private fun validateDnsAnswer(bytes: ByteArray, id: Int, host: String): Boolean {
        if (bytes.size < 12) return false
        val header = ByteBuffer.wrap(bytes)
        if ((header.short.toInt() and 0xffff) != id) return false
        val flags = header.short.toInt() and 0xffff
        val questions = header.short.toInt() and 0xffff
        val answers = header.short.toInt() and 0xffff
        header.short // authority count
        header.short // additional count
        if ((flags and 0x8000) == 0 || (flags and 0x000f) != 0 || questions != 1 || answers < 1) {
            return false
        }
        var offset = 12
        repeat(questions) {
            offset = skipDnsName(bytes, offset) ?: return false
            if (offset + 4 > bytes.size) return false
            offset += 4
        }
        val acceptedNames = mutableSetOf(host.lowercase())
        var matchingAddress = false
        repeat(answers) {
            val ownerResult = readDnsName(bytes, offset) ?: return false
            val owner = ownerResult.first.lowercase()
            offset = ownerResult.second
            if (offset + 10 > bytes.size) return false
            val type = readU16(bytes, offset)
            val recordClass = readU16(bytes, offset + 2)
            val dataLength = readU16(bytes, offset + 8)
            val dataOffset = offset + 10
            val dataEnd = dataOffset + dataLength
            if (dataEnd > bytes.size) return false
            if (recordClass == 1 && type == 5 && owner in acceptedNames) {
                val alias = readDnsName(bytes, dataOffset)?.first?.lowercase() ?: return false
                acceptedNames.add(alias)
            } else if (recordClass == 1 && type == 1) {
                if (dataLength != 4 || owner !in acceptedNames) return false
                matchingAddress = true
            }
            offset = dataEnd
        }
        return matchingAddress
    }

    private fun skipDnsName(bytes: ByteArray, offset: Int): Int? = readDnsName(bytes, offset)?.second

    private fun readDnsName(bytes: ByteArray, start: Int): Pair<String, Int>? {
        if (start !in bytes.indices) return null
        val labels = mutableListOf<String>()
        val visited = mutableSetOf<Int>()
        var cursor = start
        var next = -1
        repeat(128) {
            if (cursor !in bytes.indices || !visited.add(cursor)) return null
            val length = bytes[cursor].toInt() and 0xff
            if (length == 0) {
                if (next < 0) next = cursor + 1
                return labels.joinToString(".") to next
            }
            if ((length and 0xc0) == 0xc0) {
                if (cursor + 1 >= bytes.size) return null
                val target = ((length and 0x3f) shl 8) or (bytes[cursor + 1].toInt() and 0xff)
                if (next < 0) next = cursor + 2
                cursor = target
            } else {
                if (length > 63 || cursor + 1 + length > bytes.size) return null
                labels.add(String(bytes, cursor + 1, length, Charsets.US_ASCII))
                cursor += 1 + length
            }
        }
        return null
    }

    private fun readU16(bytes: ByteArray, offset: Int): Int {
        return ((bytes[offset].toInt() and 0xff) shl 8) or (bytes[offset + 1].toInt() and 0xff)
    }

    private fun activeDnsServers(): List<String> {
        return try {
            val active = connectivityManager.activeNetwork
            val properties = active?.let(connectivityManager::getLinkProperties)
            properties?.dnsServers
                ?.mapNotNull(::formatAddress)
                ?.distinct()
                ?: emptyList()
        } catch (error: SecurityException) {
            Log.w(TAG, "Cannot read Android DNS configuration: ${error.message}")
            emptyList()
        } catch (error: RuntimeException) {
            Log.w(TAG, "Android network state unavailable: ${error.message}")
            emptyList()
        }
    }

    private fun formatAddress(address: InetAddress): String? {
        val value = address.hostAddress?.trim().orEmpty()
        if (value.isEmpty() || value.any { it == '\n' || it == '\r' || it.isWhitespace() }) return null
        return value
    }

    private fun writeIfChanged(target: File, content: String, mode: Int) {
        if (target.isFile && target.readText() == content) return
        target.parentFile?.mkdirs()
        val temporary = File(target.parentFile, ".${target.name}.${android.os.Process.myPid()}.tmp")
        try {
            temporary.writeText(content)
            android.system.Os.chmod(temporary.absolutePath, mode)
            android.system.Os.rename(temporary.absolutePath, target.absolutePath)
        } finally {
            if (temporary.exists()) temporary.delete()
        }
    }

    private fun copyIfChanged(source: File, target: File) {
        if (target.isFile && target.length() == source.length() &&
            target.lastModified() == source.lastModified()) return
        target.parentFile?.mkdirs()
        val temporary = File(target.parentFile, ".${target.name}.${android.os.Process.myPid()}.tmp")
        try {
            source.inputStream().use { input ->
                FileOutputStream(temporary).use { output -> input.copyTo(output) }
            }
            android.system.Os.chmod(temporary.absolutePath, 0b110100100) // 0644
            temporary.setLastModified(source.lastModified())
            android.system.Os.rename(temporary.absolutePath, target.absolutePath)
        } finally {
            if (temporary.exists()) temporary.delete()
        }
    }
}
